### ISSUE TITLE
Improve Bubble sort.

### ISSUE THREAD

**Issue by rupav** [caspervonb/toneofsorting#5]
Unnecessary iterations even after it gets sorted.

**How to reproduce**
Set Shuffle to ascending.
Now in the first iteration we get to know that, given input is sorted, so what is the need to iterate further.
Or was it intentional?

**Expected Behaviour**
once input gets sorted, it should stop iterating further.

I would like to work on it.

**Comment by caspervonb** [comment]
> Or was it intentional?

Kinda but it has been pointed out a ton of times on reddit so might as-well fix it :+1:

**Comment by rupav** [comment]
So will you do it or can I add the required?

**Comment by caspervonb** [comment]
Feel free to add the missing flag/early quit.
